### ISSUE TITLE
Error response from daemon: Pool overlaps with other one on this address space

### ISSUE THREAD

**Issue by 2003emachinesDesktop** [dmonizer/klipmoonsail#13]
when i run the ./buildstart.sh init i am getting an error:

`error response from daemon: Pool overlaps with other one on this address space
running only klipper for first-time config and flashing
root@d4f16820a2bb:/klipper# exit
exit
if all is correct, you should be able to run klipmoonsail now: ./buildstart.sh run
all done
`

so i go run ./buildstart.sh run and i get more errors:

`no container specified, running all
Starting klipper ... docker run --rm -d --name klipper -v /dev:/dev --device-cgroup-rule='c 188:* rmw' --device-cgroup-rule='c 81:* rmw' --user 1000: --mount type=bind,source=/home/pi/klipmoonsail/runtime/logs,target=/logs --mount type=bind,source=/home/pi/klipmoonsail/runtime/tmp,target=/tmp --mount type=bind,source=/home/pi/klipmoonsail/runtime/sdcard,target=/sdcard --mount type=bind,source=/home/pi/klipmoonsail/runtime/config,target=/klipper/config --net klipmoonsail --hostname klipper.local --ip 172.18.0.23 klipper
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/pi/klipmoonsail/runtime/logs.
See 'docker run --help'.
done
Starting moonraker ... docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/pi/klipmoonsail/runtime/logs.
See 'docker run --help'.
done
Starting mainsail ... Unable to find image 'mainsail:latest' locally
docker: Error response from daemon: pull access denied for mainsail, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
done
`

not sure how to fix this or if im doing something wrong. im running this on a pi 3 with raspbian OS lite (buster)

**Comment by 2003emachinesDesktop** [comment]
i started running the `./buildstart.sh init` as `sudo ./buildstart.sh init` and i am getting a different set of errors now

`Step 8/23 : RUN groupadd -g ${GID} 3dprinters
 ---> Running in d683f6424728
groupadd: GID '0' already exists
The command '/bin/sh -c groupadd -g ${GID} 3dprinters' returned a non-zero code: 4
Error response from daemon: Pool overlaps with other one on this address space
running only klipper for first-time config and flashing
root@777a8e898561:/klipper# exit
`

**Comment by dmonizer** [comment]
first - u should not run it with sudo.
of the initial problem   - see that rhere is a directory  /home/pi/klipmoonsail/runtime/logs
