### ISSUE TITLE
python-virtualenv dependency in moonraker

### ISSUE THREAD

**Issue by KaruroChori** [dmonizer/klipmoonsail#7]
The original dependency _python-virtualenv_ is now _python3-virtualenv_ from _python:3_.
The building process of the container will fail otherwise.

**Comment by KaruroChori** [comment]
Also, we need  _libsodium_ or the authorization plugin will fail.

**Comment by dmonizer** [comment]
Thank you. Feel free to open PR to correct these

**Comment by KaruroChori** [comment]
PR here: #8
